version: "3"

services: 
    mongo: 
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - '27017:27017'
       
    app:
        build: .
        command: npm start
        ports: 
            - "4000:4000"
        volumes: 
            - .:/usr/app
        depends_on: 
            - mongo